const subjects = {
  C1: false,
  APC: false,
  DIAC: false,
  EA: false,
  IE: false,
  C2: false,
  Física1: false,
  FisicaExperimental1: false,
  IAL: false,
  PE: false,
  DS: false,
  Métodos: false,
  EE: false,
  Humanidades: false,
  TED1: false,
  PED1: false,
  OO: false,
  MD1: false,
  GPEQ: false,
  MDS: false,
  EDA1: false,
  FAC: false,
  MD2: false,
  PI1: false,
  IHC: false,
  Requisitos: false,
  SBD1: false,
  FSO: false,
  Compiladores1: false,
  EDA2: false,
  Qualidade: false,
  Testes: false,
  Desenho: false,
  FRC: false,
  SBD2: false,
  PA: false,
  TecProg: false,
  Paradigmas: false,
  FSE: false,
  PPD: false,
  EPS: false,
  GCES: false,
  Estágio: false,
  PI2: false,
  TCC1: false,
  TCC2: false,
};

const priorities = {
  APC: ["DS", "OO", "EDA1"],
  C1: ["C2", "PE", "PA"],
  EA: [],
  DIAC: ["IHC"],
  IE: [],
  C2: ["Métodos"],
  Física1: [],
  FisicaExperimental1: [],
  IAL: ["TED1", "PED1"],
  PE: [],
  DS: [],
  Métodos: [],
  EE: ["GPEQ"],
  Humanidades: [],
  TED1: ["FAC"],
  PED1: [],
  OO: ["MDS", "PI1", "Paradigmas"],
  MD1: ["MD2"],
  GPEQ: ["Qualidade"],
  MDS: ["IHC", "Requisitos", "Testes"],
  EDA1: ["Compiladores1", "EDA2", "PA"],
  FAC: ["FSO"],
  MD2: ["SBD1"],
  PI1: [],
  IHC: ["Qualidade"],
  Requisitos: ["Desenho"],
  SBD1: ["SBD2"],
  FSO: ["FRC", "FSE"],
  Compiladores1: ["Paradigmas"],
  EDA2: ["PPD"],
  Qualidade: [],
  Testes: ["TecProg", "GCES"],
  Desenho: ["TecProg"],
  FRC: ["PPD"],
  SBD2: [],
  PA: [],
  TecProg: ["EPS"],
  Paradigmas: [],
  FSE: [],
  PPD: [],
  EPS: [],
  GCES: [],
  Estágio: [],
  PI2: [],
  TCC1: ["TCC2"],
  TCC2: [],
};

export { subjects, priorities };
